name: PR Validation - Terraform

on:
  pull_request:
    branches: [main]
    paths:
      - 'infra/**'

jobs:
  validate:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: infra
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: terraform init -backend=false -input=false
      - run: terraform validate
      - run: terraform fmt -check -recursive
